Try whether the Debian keyring is available with a .pgp extension
In preparation for the Debian keyrings being provided with .pgp
extensions in addition to .gpg ones (at least for a transition period),
let's look for both of them.

See: https://bugs.debian.org/1092980

diff --git a/update-grml-rescueboot b/update-grml-rescueboot
--- a/update-grml-rescueboot
+++ b/update-grml-rescueboot
@@ -20,9 +20,16 @@ for binary in "${!bin_to_pkg[@]}" ; do
 done
 
 keyringname="/usr/share/keyrings/debian-keyring"
-keyring="${keyringname}.gpg"
+keyring=""
+for pgpext in pgp gpg; do
+  keyring="${keyringname}.${pgpext}"
+  if [ -r "${keyring}" ] ; then
+    break
+  fi
+  keyring=""
+done
 if [ -z "${keyring}" ] ; then
-  echo "ERROR: File ${keyringname}.gpg not found." >&2
+  echo "ERROR: File ${keyringname}.{pgp,gpg} not found." >&2
   missing_packages+=( debian-keyring )
 fi
 
